
// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5265.Robot01.commands;

import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc5265.Robot01.Robot;
import org.usfirst.frc5265.Robot01.RobotMap;

/**
 *
 */
public class Clamp extends Command {
	double clampTime;
	double clampPower;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public Clamp() {

    	requires(Robot.ballShooter);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        }

        // Called just before this Command runs the first time
        protected void initialize() {
        	clampPower = SmartDashboard.getNumber("clamp power");
         	clampTime = SmartDashboard.getNumber("clamp time");
         	RobotMap.ballShooterShooting.setSafetyEnabled(false);         	
         	Robot.ballShooter.on(clampPower);
  

        }

        // Called repeatedly when this Command is scheduled to run
        protected void execute() {

//      	Robot.ballShooter.on(shooterPower);
        	
        }

        // Make this return true when this Command no longer needs to run execute()
        protected boolean isFinished() {
        	Timer.delay(clampTime);
        	Robot.ballShooter.stop();
        	RobotMap.ballShooterShooting.setSafetyEnabled(true);         	
         	return true;
        }

        // Called once after isFinished returns true
        protected void end() {
        
     //   Robot.ballShooter.stop();
        }

        // Called when another command which requires one or more of the same
        // subsystems is scheduled to run
        protected void interrupted() {
        	end();
        }
        
        public void log() {
        	
        	SmartDashboard.putNumber("clamp power", 1);
        	SmartDashboard.putNumber("clamp time", 1);
       	 /* shooterPower = SmartDashboard.getNumber("clamp power", -0.3);

        	shooterTime = SmartDashboard.getNumber("clamp time", 1);
        	
        	SmartDashboard.putNumber("clamp power", -0.3);
        	SmartDashboard.putNumber("clamp time", 1); */
        }
    }
